---
title: "Coordinate Vectors"
author: "Brody Erlandson"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 2
---

\include{mathCommands}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Coordinates

## Definitions and Theorems {.tabset}

### Theorem 1.1. 
**Unique Representation Theorem**

If

$$
B=\left\{\mathbf{b}_{1}, \mathbf{b}_{2}, \ldots, \mathbf{b}_{n}\right\}
$$

is a basis for a vector space $V$, then any vector $\mathbf{x}$ in $V$ can be written uniquely as a linear combination of the basis vectors. In other words, there exists a unique set of scalars

$$
\left\{c_{1}, c_{2}, \ldots, c_{n}\right\}
$$

such that

$$
\mathbf{x}=\sum_{i=1}^{n} c_{i} \mathbf{b}_{i}
$$


### Definition 1.1.

Let $B=\left\{\mathbf{b}_{1}, \mathbf{b}_{2}, \ldots, \mathbf{b}_{n}\right\}$ be a basis for a vector space $V$ and let $\mathbf{x}$ be in $V$. Then the coordinate vector of $\mathbf{x}$ relative to the basis $B$ is

$$
\rho_{B}(\mathbf{x})=\left[\begin{array}{c}
c_{1} \\
c_{2} \\
\vdots \\
c_{n}
\end{array}\right]
$$

where

$$
\mathbf{x}=\sum_{i=1}^{n} c_{i} \mathbf{b}_{i}
$$

Note that because of the Unique Representation Theorem, every vector $\mathbf{x}$ in a vector space $V$ has a corresponding unique coordinate vector $\rho_{B}(\mathbf{x})$. This describes a mapping from $V$ to $\mathbb{C}^{n}$, where $n$ is the number of vectors in the basis for $V$, and the number of entries in $\rho_{B}(\mathbf{x})$. We can write this mapping as

$$
\rho_{B}: V \rightarrow \mathbb{C}^{n} \quad \text { or } \quad \mathbf{x} \mapsto \rho_{B}(\mathbf{x})
$$

More on this later.

## Examples

### Coordinates in $\mathbb C^n$

Let $B=\left\{\left[\begin{array}{l}3 \\ 2\end{array}\right],\left[\begin{array}{r}-4 \\ 1\end{array}\right]\right\}$, and $\mathbf{x}=\left[\begin{array}{l}5 \\ 7\end{array}\right]$. Find $\rho_{B}(\mathbf{x})$.

<details><summary>Solution</summary>

$$
\mathbf{x}=c_{1} \mathbf{b}_{1}+c_{2} \mathbf{b}_{2}=c_{1}\left[\begin{array}{l}
3 \\
2
\end{array}\right]+c_{2}\left[\begin{array}{r}
-4 \\
1
\end{array}\right]=\left[\begin{array}{l}
5 \\
7
\end{array}\right]
$$

We solve this vector equation by writing it as a matrix equation and row reducing the augmented matrix:

$$
\begin{gathered}
{\left[\begin{array}{rr}
3 & -4 \\
2 & 1
\end{array}\right]\left[\begin{array}{l}
c_{1} \\
c_{2}
\end{array}\right]=\left[\begin{array}{l}
5 \\
7
\end{array}\right]} \\
{\left[\begin{array}{rrr}
3 & -4 & 5 \\
2 & 1 & 7
\end{array}\right] \sim\left[\begin{array}{lll}
1 & 0 & 3 \\
0 & 1 & 1
\end{array}\right]}
\end{gathered}
$$

$\mathrm{So}$

$$
\rho_{B}(\mathbf{x})=\left[\begin{array}{l}
c_{1} \\
c_{2}
\end{array}\right]=\left[\begin{array}{l}
3 \\
1
\end{array}\right]
$$

</details>

Let

$$
\mathbf{x}=\left[\begin{array}{r}
2 \\
-1 \\
6
\end{array}\right]
$$

Find $\rho_{E}(\mathbf{x})$, where $E$ is the standard basis for $\mathbb{C}^{3}$.

<details><summary>Solution</summary>

Here we have

$$
\mathbf{x}=c_{1} \mathbf{e}_{1}+c_{2} \mathbf{e}_{2}+c_{3} \mathbf{e}_{3}
$$

and substituting in for $\mathbf{x}$ and the basis vectors we get

$$
\left[\begin{array}{r}
2 \\
-1 \\
6
\end{array}\right]=c_{1}\left[\begin{array}{l}
1 \\
0 \\
0
\end{array}\right]+c_{2}\left[\begin{array}{l}
0 \\
1 \\
0
\end{array}\right]+c_{3}\left[\begin{array}{l}
0 \\
0 \\
1
\end{array}\right]
$$

By observation we can see that

$$
\begin{aligned}
&c_{1}=x_{1}=2 \\
&c_{2}=x_{2}=-1 \\
&c_{3}=x_{3}=6
\end{aligned}
$$

So

$$
\rho_{E}(\mathbf{x})=\mathbf{x}=\left[\begin{array}{r}
2 \\
-1 \\
6
\end{array}\right]
$$

</details>

### Coordinates in $\mathbb P_n$

Let $B=\left\{x^{2}, x, 1\right\}$, the standard basis for $\mathbb P_{2}$, and let

$$
\mathbf{p}=3 x^{2}-6 x-2
$$

Find $\rho_{B}(\mathbf{p})$.

<details><summary>Solution</summary>

We need to solve $\mathbf{p}=c_{1} \mathbf{b}_{1}+c_{2} \mathbf{b}_{2}+c_{3} \mathbf{b}_{3}$, where $\mathbf{b}_{1}=x^{2}, \mathbf{b}_{2}=x$, and $\mathbf{b}_{3}=1$.

Since $\mathbf{p}$ is already a linear combination of the basis vectors, we can find the coordinate vector relative to this basis by observation. We have:

$$
\begin{aligned}
\mathbf{p} &=c_{1} \mathbf{b}_{1}+c_{2} \mathbf{b}_{2}+c_{3} \mathbf{b}_{3} \\
&=c_{1} x^{2}+c_{2} x+c_{3}(1) \\
&=3 x^{2}-6 x-2
\end{aligned}
$$

So

$$
\rho_{B}(\mathbf{p})=\left[\begin{array}{l}
c_{1} \\
c_{2} \\
c_{3}
\end{array}\right]=\left[\begin{array}{r}
3 \\
-6 \\
-2
\end{array}\right]
$$

Now consider a non-standard basis for $P_{2}$.

</details>

Let

$$
D=\left\{2 x^{2}-x, x+1,5\right\}, \text { and } \mathbf{p}=3 x^{2}-6 x-2
$$

as in the previous example. Find $\rho_{D}(\mathbf{p})$

<details><summary>Solution</summary>

We need to solve $\mathbf{p}=c_{1} \mathbf{d}_{1}+c_{2} \mathbf{d}_{2}+c_{3} \mathbf{d}_{3}$, where $\mathbf{d}_{1}=2 x^{2}-x, \mathbf{d}_{2}=x+1$, and $\mathbf{d}_{3}=5$

So we have:

$$
\begin{aligned}
\mathbf{p} &=c_{1} \mathbf{d}_{1}+c_{2} \mathbf{d}_{2}+c_{3} \mathbf{d}_{3} \\
3 x^{2}-6 x-2 &=c_{1}\left(2 x^{2}-x\right)+c_{2}(x+1)+c_{3}(5) \\
3 x^{2}-6 x-2 &=2 c_{1} x^{2}-c_{1} x+c_{2} x+c_{2}+5 c_{3} \\
3 x^{2}-6 x-2 &=2 c_{1} x^{2}+\left(-c_{1}+c_{2}\right) x+\left(c_{2}+5 c_{3}\right)
\end{aligned}
$$

Setting like terms on both sides of this equation equal gives:

$$
\begin{aligned}
3 &=2 c_{1} \\
-6 &=-c_{1}+c_{2} \\
-2 &=c_{2}+5 c_{3}
\end{aligned}
$$

Writing this system of equations in the standard form, including the zero terms gives:

$$
\begin{aligned}
2 c_{1} &=3 \\
-c_{1}+c_{2}&=-6 \\
c_{2}+5 c_{3} &=-2
\end{aligned}
$$

And of course we solve this system by row-reducing the augmented matrix:

$$
\begin{aligned}
{\left[\begin{array}{rrrr}
2 & 0 & 0 & 3 \\
-1 & 1 & 0 & -6 \\
0 & 1 & 5 & -2
\end{array}\right] \sim\left[\begin{array}{rrrr}
1 & 0 & 0 & 1.5 \\
0 & 1 & 0 & -4.5 \\
0 & 0 & 1 & 0.5
\end{array}\right] } \\
\Longrightarrow & c_{1}=1.5 \\
c_{2} &=-4.5 \\
c_{3} &=0.5
\end{aligned}
$$

$$
\rho_{D}(\mathbf{p})=\left[\begin{array}{l}
c_{1} \\
c_{2} \\
c_{3}
\end{array}\right]=\left[\begin{array}{r}
1.5 \\
-4.5 \\
0.5
\end{array}\right]
$$

</details>

# Isomorphism From $V$ to $\mathbb C^n$

## Definitions and Theorems {.tabset}

### Definition 4.1.
**Coordinate Vector Transformation**

Let $V$ be an n-dimensional vector space with basis $B$. The transformation

$$
\rho_{B}: V \rightarrow \mathbb{C}^{n}
$$

is the coordinate vector transformation for $V$ relative to $B$.

Recall that $\rho_{B}(\mathbf{x})$ is the coordinate vector of $\mathbf{x}$ relative to the basis $B$ :

$$
\rho_{B}(\mathbf{x})=\left[\begin{array}{c}
c_{1} \\
c_{2} \\
\vdots \\
c_{n}
\end{array}\right]
$$

where

$$
\mathbf{x}=\sum_{i=1}^{n} c_{i} \mathbf{b}_{i}
$$

Now we're interpreting $\rho_{B}(\mathbf{x})$ as the image of $\mathbf{x}$ under the linear transformation $\rho_{B}$

### Theorem 4.1. 

If $B=\left\{\mathbf{b}_{1}, \mathbf{b}_{2}, \ldots, \mathbf{b}_{n}\right\}$ is a basis for a vector space $V$, then

$$
\rho_{B}: V \rightarrow \mathbb{C}^{n}
$$

is an isomporphism. 

<details><summary>*Proof*</summary> 

We need to show that $\rho_{B}$ is linear, one-to-one, and onto. Let $\mathbf{x}$ and $\mathbf{y}$ be vectors in $V$, and let $\alpha$ and $\beta$ be scalars. By the Unique Representation Theorem, there are unique coordinate vectors $\rho_{B}(\mathbf{x})$ and $\rho_{B}(\mathbf{y})$.

Let

$$
\rho_{B}(\mathbf{x})=\left[\begin{array}{c}
a_{1} \\
\vdots \\
a_{n}
\end{array}\right] \quad \text { and } \quad \rho_{B}(\mathbf{y})=\left[\begin{array}{c}
c_{1} \\
\vdots \\
c_{n}
\end{array}\right]
$$

Then we have:

$$
\begin{aligned}
\rho_{B}(\alpha \mathbf{x}+\beta \mathbf{y})=& \rho_{B}\left(\alpha \sum_{i=1}^{n} a_{i} \mathbf{b}_{i}+\beta \sum_{i=1}^{n} c_{i} \mathbf{b}_{i}\right) \\
=& \rho_{B}\left(\sum_{i=1}^{n} \alpha a_{i} \mathbf{b}_{i}+\sum_{i=1}^{n} \beta c_{i} \mathbf{b}_{i}\right) \\
=& \rho_{B}\left(\sum_{i=1}^{n}\left(\alpha a_{i}+\beta c_{i}\right) \mathbf{b}_{i}\right) \\
=& {\left[\begin{array}{c}
\alpha a_{1}+\beta c_{1} \\
\vdots \\
\alpha a_{n}+\beta c_{n}
\end{array}\right]=\alpha\left[\begin{array}{c}
a_{1} \\
\vdots \\
a_{n}
\end{array}\right]+\beta\left[\begin{array}{c}
c_{1} \\
\vdots \\
c_{n}
\end{array}\right] } \\
=& \alpha \rho_{B}(\mathbf{x})+\beta \rho_{B}(\mathbf{y})
\end{aligned}
$$

So $\rho_{B}$ is linear.

To show that $\rho_{B}$ is one-to-one, we need to show that every vector in $\mathbb{C}^{n}$ corresponds to at most one vector in $V$. Assume there are two vectors $\mathbf{x}$ and $\mathbf{w}$ in $V$ that have the same coordinate vector, i.e.

$$
\rho_{B}(\mathbf{x})=\rho_{B}(\mathbf{w})=\left[\begin{array}{c}
d_{1} \\
\vdots \\
d_{n}
\end{array}\right]
$$

Then

$$
\mathbf{x}=\sum_{i=1}^{n} d_{i} \mathbf{b}_{i}=\mathbf{w}
$$

So if

$$
\rho_{B}(\mathbf{x})=\rho_{B}(\mathbf{w})
$$

then

$$
\mathbf{x}=\mathbf{w}
$$

Therefore $\rho_{B}$ is one-to-one.

Finally, consider an arbitrary vector

$$
\mathbf{z}=\left[\begin{array}{c}
z_{1} \\
\vdots \\
z_{n}
\end{array}\right] \in \mathbb{C}^{n}
$$

Let

$$
\mathbf{x}=\sum_{i=1}^{n} z_{i} \mathbf{b}_{i}
$$

Since $\mathbf{x}$ is a linear combination of basis vectors for $V, \mathbf{x} \in V$. Therefore every vector $\mathbf{z} \in \mathbb{C}^{n}$ corresponds to at least one $\mathbf{x} \in V$, and $\rho_{B}$ is onto.

Since $\rho_{B}$ is linear, one-to-one, and onto, it is an isomorphism.

</details>

### Theorem 4.2.
**Isomorphism from $V$ to $\mathbb{C}^{n}$**

Every $n$-dimensional vector space is isomorphic to $\mathbb{C}^{n}$.

<details><summary>Proof</summary>

Let $V$ be an n-dimensional vector space with basis $B$. Since

$$
\rho_{B}: V \rightarrow \mathbb{C}^{n}
$$

is an isomorphism, $V$ is isomorphic to $\mathbb{C}^{n}$. 

</details>

### Theorem 4.3. 
**Isomorphism and Linear Independence**

If $V$ is an $n$-dimensional vector space with basis $B$, and

$$
S=\left\{\mathbf{v}_{1}, \mathbf{v}_{2}, \ldots, \mathbf{v}_{n}\right\}
$$

is a subset of $V$, then $S$ is linearly independent iff

$$
R=\left\{\rho_{B}\left(\mathbf{v}_{1}\right), \rho_{B}\left(\mathbf{v}_{2}\right), \ldots, \rho_{B}\left(\mathbf{v}_{n}\right)\right\}
$$

is linearly independent.

### Theorem 4.4.
**Isomorphism and Span**

If $V$ is an $n$-dimensional vector space with basis $B$, and

$$
S=\left\{\mathbf{v}_{1}, \mathbf{v}_{2}, \ldots, \mathbf{v}_{n}\right\}
$$

is a subset of $V$, then $\langle S\rangle=V$ iff

$$
\left\langle\left\{\rho_{B}\left(\mathbf{v}_{1}\right), \rho_{B}\left(\mathbf{v}_{2}\right), \ldots, \rho_{B}\left(\mathbf{v}_{n}\right)\right\}\right\rangle=\mathbb{C}^{n}
$$

### Theorem 4.5.
**Isomorphism and Bases**

If $V$ is an $n$-dimensional vector space with basis $B$, and

$$
S=\left\{\mathbf{v}_{1}, \mathbf{v}_{2}, \ldots, \mathbf{v}_{n}\right\}
$$

is a subset of $V$, then $S$ is a basis for $V$ iff

$$
R=\left\{\rho_{B}\left(\mathbf{v}_{1}\right), \rho_{B}\left(\mathbf{v}_{2}\right), \ldots, \rho_{B}\left(\mathbf{v}_{n}\right)\right\}
$$

is a basis for $\mathbb{C}^{n}$. 

## Further Explainations

### What the Theorems Tell Us

We can summarize the above theorems by saying that *"isomorphisms preserve linear dependence relations"*. In general, this means that linear dependence relations between coordinate vectors in $\mathbb{C}^{n}$ will be the same as linear dependence relations between the corresponding vectors in $V$. In other words, linear combinations of vectors in $V$ will be mirrored by the same linear combinations of coordinate vectors in $\mathbb{C}^{n}$.

In other words, if $\mathbf{y}_{1}, \mathbf{y}_{2}, \ldots, \mathbf{y}_{p}$ are in $V$ and

$$
\mathbf{x}=\sum_{i=1}^{p} c_{i} \mathbf{y}_{i}
$$

then

$$
\rho_{B}(\mathbf{x})=\sum_{i=1}^{p} c_{i} \rho_{B}\left(\mathbf{y}_{i}\right)
$$

where $c_{i} \in \mathbb{C}$.

### "Clean" Basis for $\mathbb P_n$

 We've seen that the coordinate vector relative to the standard basis of $\mathbb{C}^{n}$ of any vector in $\mathbb{C}^{n}$ is the vector itself, or

$$
\rho_{E}(\mathbf{x})=\mathbf{x}
$$

In $\mathbb{P}_{n}$ this wouldn't work; in other words if $\mathbf{p}$ is a vector in $\mathbb{P}_{n}$ we couldn't have

$$
\rho_{D}(\mathbf{p})=\mathbf{p}
$$

for some basis $D$ of $\mathbb{P}_{n}$. This is because $\rho_{D}(\mathbf{p})$ is in $\mathbb{C}^{n}$ and $\mathbf{p}$ is in $\mathbb{P}_{n}$.

However, we can find a basis for $\mathbb{P}_{n}$ that's almost as "nice" as the standard basis for $\mathbb{C}^{n}$. Specifically we can find a basis for $\mathbb{P}_{n}$ that allows us to simply observe the coordinate vectors for vectors in $\mathbb{P}_{n}$. In particular, let's find a basis $D=\left\{\mathbf{d}_{0}, \mathbf{d}_{1}, \ldots, \mathbf{d}_{n}\right\}$ for $\mathbb{P}_{n}$ so that if

$$
\mathbf{p}(x)=a_{0}+a_{1} x+\cdots+a_{n} x^{n}
$$

then

$$
\rho_{D}(\mathbf{p})=\left[\begin{array}{c}
a_{0} \\
a_{1} \\
\vdots \\
a_{n}
\end{array}\right]
$$

This implies

$$
\begin{aligned}
\mathbf{p} &=a_{0} \mathbf{d}_{0}+a_{1} \mathbf{d}_{1}+\cdots+a_{n} \mathbf{d}_{n} \\
&=a_{0}+a_{1} x+\cdots+a_{n} x^{n}
\end{aligned}
$$

This equation is satisfied if we let

$$
\begin{aligned}
\mathbf{d}_{0} &=1 \\
\mathbf{d}_{1} &=x \\
\mathbf{d}_{2} &=x^{2} \\
& \vdots \\
\mathbf{d}_{n} &=x^{n}
\end{aligned}
$$

So the basis we're looking for is $D=\left\{1, x, x^{2}, \ldots, x^{n}\right\}$, and this is the standard basis for $\mathbb{P}_{n}$ because it has the property that we can observe the coordinate vectors relative to this basis without doing any calculations.

## Examples

Let $V$ be an n-dimensional vector space with basis $B$, and let $\mathbf{x}, \mathbf{y}$, and $\mathbf{z}$ be in $V$

If

$$
\mathbf{u}=3 \mathbf{x}-7 \mathbf{y}+4 \mathbf{z}
$$

Then what is $\rho_{B}(\mathbf{u})$ equal to in terms of $\mathbf{x}, \mathbf{y}$, and $\mathbf{z}$?

<details><summary>Solution</summary>

$$
\rho_{B}(\mathbf{u})=3 \rho_{B}(\mathbf{x})-7 \rho_{B}(\mathbf{y})+4 \rho_{B}(\mathbf{z})
$$

</details>


Show that $B=\left\{1+x^{2}, x+x^{2}, 1+2 x+x^{2}\right\}$ is a basis for $\mathbb{P}_{2}$.

<details><summary>Solution</summary>

We need to show that $B$ is a linearly independent set that spans $\mathbb{P}_{2}$. Alternately, if we know that $\mathbb{P}_{2}$ is three dimensional, we could just show that $B$ is linearly independent, or that it spans $\mathbb{P}_{2}$, since it contains exactly 3 vectors. Let

$$
D=\left\{1, x, x^{2}\right\}
$$

which as we saw in the previous example is the standard basis for $\mathbb{P}_{2}$. Now let 

$$
\begin{aligned}
&\mathbf{b}_{1}=1+x^{2}=(1) 1+(0) x+(1) x^{2} \\
&\mathbf{b}_{2}=x+x^{2}=(0) 1+(1) x+(1) x^{2} \\
&\mathbf{b}_{3}=1+2 x+x^{2}=(1) 1+(2) x+(1) x^{2}
\end{aligned}
$$

So that

$$
B=\left\{\mathbf{b}_{1}, \mathbf{b}_{2}, \mathbf{b}_{3}\right\}
$$

Then as in the example above, we can just observe the coordinate vectors:

$$
\rho_{D}\left(\mathbf{b}_{1}\right)=\left[\begin{array}{c}
1 \\
0 \\
1
\end{array}\right], \quad \rho_{D}\left(\mathbf{b}_{2}\right)=\left[\begin{array}{l}
0 \\
1 \\
1
\end{array}\right], \quad \rho_{D}\left(\mathbf{b}_{3}\right)=\left[\begin{array}{c}
1 \\
2 \\
1
\end{array}\right]
$$

By theorem $4.5$ above, if

$$
\left\{\rho_{D}\left(\mathbf{b}_{1}\right), \rho_{D}\left(\mathbf{b}_{2}\right), \rho_{D}\left(\mathbf{b}_{3}\right)\right\}
$$

is a basis for $\mathbb{C}^{3}$, then $B$ is a basis for $\mathbb{P}_{2}$. To decide this, we can use IMT as follows. Let

$$
\begin{aligned}
A &=\left[\rho_{D}\left(\mathbf{b}_{1}\right)\left|\rho_{D}\left(\mathbf{b}_{2}\right)\right| \rho_{D}\left(\mathbf{b}_{3}\right)\right]\\
&=\left[\begin{array}{lll}
1 & 0 & 1 \\
0 & 1 & 2 \\
1 & 1 & 1
\end{array}\right]
\end{aligned}
$$

If $A$ is invertible, its column vectors form a basis for $\mathbb{C}^{3}$. Since

$$
A=\left[\begin{array}{lll}
1 & 0 & 1 \\
0 & 1 & 2 \\
1 & 1 & 1
\end{array}\right] \sim\left[\begin{array}{lll}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{array}\right]
$$

$A$ is invertible, $\left\{\rho_{D}\left(\mathbf{b}_{1}\right), \rho_{D}\left(\mathbf{b}_{2}\right), \rho_{D}\left(\mathbf{b}_{3}\right)\right\}$ is a basis for $\mathbb{C}^{3}$, and therefore $B=\left\{\mathbf{b}_{1}, \mathbf{b}_{2}, \mathbf{b}_{3}\right\}$ is a basis for $\mathbb{P}_{2}$

</details>
