---
title: "Determinants"
author: "Brody Erlandson"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 2
---

\renewcommand{\v}{\mathbf{v}}
\renewcommand{\u}{\mathbf{u}}
\newcommand{\w}{\mathbf{w}}
\newcommand{\vx}{\mathbf{x}}
\newcommand{\vy}{\mathbf{y}}
\newcommand{\vz}{\mathbf{z}}
\newcommand{\0}{\mathbf{0}}
\newcommand{\1}{\mathbf{1}}
\newcommand{\A}{\mathbf{A}}
\newcommand{\B}{\mathbf{B}}
\newcommand{\Cmat}{\mathbf{C}}
\newcommand{\I}{\mathbf{I}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\set}[2]{\{#1_1, #1_2, \dots, #1_#2\}}
\newcommand{\null}[1]{\mathcal{N}(#1)}
\newcommand{\col}[1]{\mathcal{C}(#1)}
\newcommand{\row}[1]{\mathcal{R}(#1)}
\newcommand{\eig}{\mathcal{E}}
\newcommand{\vdd}[2]{\begin{bmatrix} #1\\ #2 \end{bmatrix}}
\newcommand{\vddd}[3]{\begin{bmatrix} #1\\ #2\\ #3 \end{bmatrix}}
\newcommand{\vdddd}[4]{\begin{bmatrix} #1\\ #2\\ #3\\ #4 \end{bmatrix}}
\newcommand{\mdd}[4]{\begin{bmatrix} #1 & #2\\ #3 & #4 \end{bmatrix}}
\newcommand{\mddd}[9]{\begin{bmatrix} #1 & #2 & #3\\ #4 & #5 & #6\\ #7 & #8 & #9\\\end{bmatrix}}
\newcommand{\span}[1]{\langle #1 \rangle}
\newcommand{\innerProd}[2]{\langle #1, #2 \rangle}
\newcommand{\norm}[1]{\lVert #1 \rVert}
\newcommand{\dim}[1]{\text{dim}(#1)}
\newcommand{\det}{\text{det}}
\newcommand{\kernel}{\mathcal{K}}
\newcommand{\range}{\mathcal{R}}


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Determinants

## Definitions and Theorems {.tabset}

### Definition 1.1.
**Submatrix**

Let $\A$ be an $m \times n$ matrix:

$$A = \begin{bmatrix} a_{11} & \dots & a_{1j} & \dots & a_{1n} \\
                      \vdots  & \ddots & \vdots & \ddots & \vdots \\
                      a_{m1}  & \dots & a_{mj} & \dots & a_{mn} \\
      \end{bmatrix}$$

Then the submatrix $\A(i|j)$ is the matrix $\A$ with row $i$ and column $j$ deleted:

$$A(i|j) = \begin{bmatrix} a_{11} & \dots & a_{1(j-1)} & a_{1(j+1)} & \dots & a_{1n} \\
                      \vdots  & \ddots & \vdots & \vdots & \ddots & \vdots \\
                      a_{(j-1)1}  & \dots & a_{(j-1)(j-1)} & a_{(j-1)(j+1)} & \dots & a_{(j-1)n} \\
                      a_{(j+1)1}  & \dots & a_{(j+1)(j-1)} & a_{(j+1)(j+1)} & \dots & a_{(j+1)n} \\
                      \vdots  & \ddots & \vdots & \vdots & \ddots & \vdots \\
                      a_{m1}  & \dots & a_{m(j-1)} & a_{m(j+1)} & \dots & a_{mn} \\
      \end{bmatrix}$$

### Definition 1.2.
**Determinant**

Given an $n \times n$ matrix $\A$, where $n \ge 2$, the determinant of $\A$, written 

$$\det(\A) = |\A|$$

is

$$\det(\A) = \sum_{j=1}^n (−1)^{1+j} a_{1j} \det(\A(1|j))$$

If $n = 1$ then $\det(\A) = a_{11}$.

### Theorem 1.1.

If $\A$ is a $2 \times 2$ matrix then

$$ \Bigg|\mdd{a}{b}{c}{d}\Bigg| = ad − bc$$

### Theorem 1.2.

The determinant of an $n \times n$ matrix can be computed by expanding across any row or down any column.

### Definition 2.1. 
**Upper Triangular Matrix**

An $n \times n$ matrix $\A$ is upper triangular if it has the form

$$
    \left[
    \begin{array}{ccccc}
    a_{11}                                    \\
          & a_{22}    &       & \huge{*}      \\
          &           & a_{33}                \\
          & \huge{0}  &       & \ddots        \\
          &           &       &         & a_{nn}
    \end{array}
    \right]
$$

### Definition 2.2. 
**Lower Triangular Matrix**

An $n \times n$ matrix $\A$ is lower triangular if it has the form

$$
    \left[
    \begin{array}{ccccc}
    a_{11}                                    \\
          & a_{22}    &       & \huge{0}      \\
          &           & a_{33}                \\
          & \huge{*}  &       & \ddots        \\
          &           &       &         & a_{nn}
    \end{array}
    \right]
$$

### Theorem 2.1. 

Let $\A$ be an $n \times n$ matrix. If $\A$ is triangular, then

$$\det(\A) = \prod_{i=1}^n a_{ii}$$

<details><summary>*Proof*</summary>  

For a lower triangle matrix $\A$ then we can go across the rows, and for a upper triangle matrix $\A$ then we can go across the columns. Then,

$$\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} \det(A(1|j)) 
\\ = a_{11}\det(A(1|1)) + 0\det(A(1|2)) + \dots + 0\det(A(1|n)) 
\\ = a_{11}\det(A(1|1)) = \dots = a_{11}a_{22}\dots a_{nn}$$

</details> \newline 

### Theorem 2.2.
**Row Operations and Determinants**

Let $\A$ be an $n \times n$ matrix.

a) If a multiple of one row of $\A$ is added to another row to produce matrix $\B$, then $\det(\B) = \det(\A)$.
b) If two rows of $\A$ are interchanged to produce $\B$, then $\det(\B) = − \det(\A)$.
c) If one row of $\A$ is multiplied by the scalar $\alpha$ to produce $\B$, then $\det(\B) = \alpha \det(\A)$.

### Theorem 2.3.

Let $\A$ be an $n \times n$ matrix. Then $\A$ is invertible iff $\det(\A) \not= 0$.

<details><summary>*Proof*</summary> 

Let $\A \sim \I_n$, then this implies $\A$ is invertible. Using theorem 2.2, then:
 
$$\text{by a) }\det(\B) = \det(\A) \Rightarrow \det(\I_n) = 1 = \det(\A)
\\ \text{by b) }\det(\B) = − \det(\A) \Rightarrow \det(\I_n) = 1 = -\det(\A)
\\ \text{by c) }\det(\B) = \alpha \det(\A) \Rightarrow \det(\I_n) = 1 = \alpha\det(\A)
\\ \Rightarrow \det(\A) \not= 0$$
 
</details> \newline 

### Theorem 2.4. 

If $\A$ is an $n \times n$ matrix, then $\det(\A^T) = \det(\A)$.

### Theorem 2.5. 

If $\A$ and $\B$ are $n \times n$ matrices, then $\det(\A\B) = \det(\A) \det(\B)$.

## Examples

Let

$$
A=\left[\begin{array}{cccc}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16
\end{array}\right]
$$

What is $A(2 \mid 3)$

<details><summary>Solution</summary>

$$
A(2 \mid 3)=\left[\begin{array}{ccc}
1 & 2 & 4 \\
9 & 10 & 12 \\
13 & 14 & 16
\end{array}\right]
$$

</details>

Compute the determinant

$$
\left|\begin{array}{rrr}
2 & 0 & -1 \\
5 & -3 & 3 \\
1 & 2 & -2
\end{array}\right|
$$

<details><summary>Solution</summary>

Using the definition of the determinant we have:

$$
\begin{aligned}
\left|\begin{array}{rrr}
2 & 0 & -1 \\
5 & -3 & 3 \\
1 & 2 & -2
\end{array}\right| &=2\left|\begin{array}{rr}
-3 & 3 \\
2 & -2
\end{array}\right|-0\left|\begin{array}{rr}
5 & 3 \\
1 & -2
\end{array}\right|+(-1)\left|\begin{array}{rr}
5 & -3 \\
1 & 2
\end{array}\right| \\
&=2[(-3)(-2)-2(3)]-0-[5(2)-(-3) 1] \\
&=2[6-6]-[10+3] \\
&=0-13 \\
&=-13
\end{aligned}
$$

In general, to compute the determinant of an $n \times n$ matrix, we must compute

$$
\frac{n !}{2}
$$

$2 \times 2$ determinants. That may not seem like a lot at first glance, but consider some examples.

Computing a $3 \times 3$ determinant requires computing

$$
\frac{3 !}{2}=\frac{6}{2}=3 \quad 2 \times 2 \text { determinants. }
$$

Computing a $4 \times 4$ determinant requires computing

$$
\frac{4 !}{2}=\frac{24}{2}=12 \quad 2 \times 2 \text { determinants. }
$$

Computing a $5 \times 5$ determinant requires computing

$$
\frac{5 !}{2}=\frac{120}{2}=60 \quad 2 \times 2 \text { determinants }
$$

Computing a $6 \times 6$ determinant requires computing

$$
\frac{6 !}{2}=\frac{720}{2}=360 \quad 2 \times 2 \text { determinants }
$$

Computing a $10 \times 10$ determinant requires computing

$$
\frac{10 !}{2}=\frac{3628800}{2}=1814400 \quad 2 \times 2 \text { determinants } .
$$

Even using a computer, this can get out of hand very quickly, and even be impossible on a computer for matrices where $n$ is in the thousands, which is very common in applications.

When $n=100$, which is relatively small for some applications,

$$
100 ! \approx 9 \times 10^{157}
$$

This number is literally incomprehensible. Nothing in our human experience can give a sense of its size. The number of particles in the universe was estimated a few years ago by a physicist who came up with about

$$
3 \times 10^{80}
$$

Needless to say, it would take more time than the universe has existed for the fastest computer to do $10^{157}$ computations, let alone $2 \times 2$ determinants. Fortunately, there are lots of ways around this, including the next theorem. Theorem 1.2. The determinant of an $n \times n$ matrix can be computed by expanding across any row or down any column.

</details>

Let

$$
A=\left[\begin{array}{rrrr}
-1 & 3 & 0 & 7 \\
5 & -2 & 3 & -4 \\
0 & 1 & 0 & 0 \\
2 & 8 & 0 & -2
\end{array}\right]
$$

Find $\operatorname{det}(A)$

<details><summary>Solution</summary>

Expanding down column 3:

$$
\left|\begin{array}{rrrr}
-1 & 3 & 0 & 7 \\
5 & -2 & 3 & -4 \\
0 & 1 & 0 & 0 \\
2 & 8 & 0 & -2
\end{array}\right|=(-3)\left|\begin{array}{rrr}
-1 & 3 & 7 \\
0 & 1 & 0 \\
2 & 8 & -2
\end{array}\right|=(-3)(1)\left|\begin{array}{rr}
-1 & 7 \\
2 & -2
\end{array}\right|=(-3)[(-1)(-2)-(2)(7)]=36
$$

Or expanding across row 3 :

$$
\left|\begin{array}{rrrr}
-1 & 3 & 0 & 7 \\
5 & -2 & 3 & -4 \\
0 & 1 & 0 & 0 \\
2 & 8 & 0 & -2
\end{array}\right|=(-1)\left|\begin{array}{rrr}
-1 & 0 & 7 \\
5 & 3 & -4 \\
2 & 0 & -2
\end{array}\right|=(-1)(3)\left|\begin{array}{rr}
-1 & 7 \\
2 & -2
\end{array}\right|=(-3)[(-1)(-2)-(2)(7)]=36
$$

</details>
