---
title: "Kernel, Range, and Isomorphism"
author: "Brody Erlandson"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 2
---



```{=tex}
\usepackage{amsfonts}
\usepackage{amsmath}
```
```{=tex}
\renewcommand{\v}{\mathbf{v}}
\renewcommand{\u}{\mathbf{u}}
\newcommand{\w}{\mathbf{w}}
\newcommand{\vx}{\mathbf{x}}
\newcommand{\vy}{\mathbf{y}}
\newcommand{\vz}{\mathbf{z}}
\newcommand{\0}{\mathbf{0}}
\newcommand{\1}{\mathbf{1}}
```
```{=tex}
\newcommand{\A}{\mathbf{A}}
\newcommand{\B}{\mathbf{B}}
\newcommand{\Cmat}{\mathbf{C}}
\newcommand{\I}{\mathbf{I}}
```
```{=tex}
\newcommand{\N}{\mathbb{N}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\set}[2]{\{#1_1, #1_2, \dots, #1_#2\}}
```
```{=tex}
\newcommand{\null}[1]{\mathcal{N}(#1)}
\newcommand{\col}[1]{\mathcal{C}(#1)}
\newcommand{\row}[1]{\mathcal{R}(#1)}
\newcommand{\eig}{\mathcal{E}}
```
```{=tex}
\newcommand{\vdd}[2]{\begin{bmatrix} #1\\ #2 \end{bmatrix}}
\newcommand{\vddd}[3]{\begin{bmatrix} #1\\ #2\\ #3 \end{bmatrix}}
\newcommand{\vdddd}[4]{\begin{bmatrix} #1\\ #2\\ #3\\ #4 \end{bmatrix}}
```
```{=tex}
\newcommand{\mdd}[4]{\begin{bmatrix} #1 & #2\\ #3 & #4 \end{bmatrix}}
\newcommand{\mddd}[9]{\begin{bmatrix} #1 & #2 & #3\\ #4 & #5 & #6\\ #7 & #8 & #9\\\end{bmatrix}}
```
```{=tex}
\newcommand{\span}[1]{\langle #1 \rangle}
\newcommand{\innerProd}[2]{\langle #1, #2 \rangle}
\newcommand{\norm}[1]{\lVert #1 \rVert}
\newcommand{\dim}[1]{\text{dim}(#1)}
\newcommand{\det}{\text{det}}
\newcommand{\kernel}{\mathcal{K}}
\newcommand{\range}{\mathcal{R}}
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Kernel and Range

## Definitions and Theorems {.tabset}

### Definition 1.1.

Let $T : U \rightarrow V$ be a linear transformation. The **kernel** of $T$ is

$$\mathcal{K}(T) = \{\mathbf{u}\in U : T(\mathbf{u}) = \mathbf{0}\}$$

### Definition 1.2.

Let $T : U \rightarrow V$ be a linear transformation. The range of $T$ is

$$\mathcal{R}(T) = \{T(\mathbf{u}) \in V : \mathbf{u}\in U\}$$

### Theorem 1.1.

**Kernel and Preimage**

Let $T : U \rightarrow V$ be a linear transformation and let $\mathbf{v}\in V$. If $T^{−1}(\mathbf{v})$ is nonempty and $\mathbf{u}\in T^{−1}(\mathbf{v})$, then

$$T^{−1}(\mathbf{v}) = \{\mathbf{u}+ \mathbf{z}| \mathbf{z}\in \mathcal{K}(T)\}$$

## Examples

Let $T: \mathbb{P}_{2} \rightarrow \mathbb{C}^{3}$, where $T(\mathbf{p})=\left[\begin{array}{l}p(0) \\ p(0) \\ p(2)\end{array}\right]$.

Find $\mathcal{K}(T)$ and $\mathcal{R}(T)$

<details>

<summary>

Solution

</summary>

An arbitrary polynomial (vector) in $\mathbb{P}_{2}$ can be written as $\mathbf{p}=p(x)=a_{0}+a_{1} x+a_{2} x^{2}, \quad a_{i} \in \mathbb{C}$, so

$$
\begin{aligned}
& T(\mathbf{p})=\mathbf{0} \\
& \Rightarrow T(\mathbf{p})=\left[\begin{array}{l}p(0) \\p(0) \\p(2)\end{array}\right]=\left[\begin{array}{l}a_{0}+a_{1}(0)+a_{2}(0)^{2} \\a_{0}+a_{1}(0)+a_{2}(0)^{2} \\a_{0}+a_{1}(2)+a_{2}(2)^{2}\end{array}\right]=\left[\begin{array}{l}0 \\0 \\0\end{array}\right] \\
& \Rightarrow\left[\begin{array}{c}a_{0} \\a_{0} \\a_{0}+2 a_{1}+4 a_{2}\end{array}\right]=\left[\begin{array}{l}0 \\0 \\0\end{array}\right] 
\end{aligned}
$$

thus

$$
\mathcal{K}(T)=\left\langle\left\{-2 x+x^{2}\right\}\right\rangle
$$

To find a spanning set for $\mathcal{R}(T)$, from the definition we know an arbitrary vector in $\mathcal{R}(T)$ is

$$
\begin{aligned}
T(\mathbf{p}) &=\left[\begin{array}{l}
p(0) \\
p(0) \\
p(2)
\end{array}\right]=\left[\begin{array}{l}
a_{0}+a_{1}(0)+a_{2}(0)^{2} \\
a_{0}+a_{1}(0)+a_{2}(0)^{2} \\
a_{0}+a_{1}(2)+a_{2}(2)^{2}
\end{array}\right] \\
&=\left[\begin{array}{c}
a_{0} \\
a_{0} \\
a_{0}+2 a_{1}+4 a_{2}
\end{array}\right] \\
=& a_{0}\left[\begin{array}{l}
1 \\
1 \\
1
\end{array}\right]+a_{1}\left[\begin{array}{l}
0 \\
0 \\
2
\end{array}\right]+a_{2}\left[\begin{array}{l}
0 \\
0 \\
4
\end{array}\right]
\end{aligned}
$$

Therefore

$$
\mathcal{R}(T)=\left\langle\left\{\left[\begin{array}{l}
1 \\
1 \\
1
\end{array}\right],\left[\begin{array}{l}
0 \\
0 \\
2
\end{array}\right],\left[\begin{array}{l}
0 \\
0 \\
4
\end{array}\right]\right\}\right\rangle=\left\langle\left\{\left[\begin{array}{l}
1 \\
1 \\
1
\end{array}\right],\left[\begin{array}{l}
0 \\
0 \\
2
\end{array}\right]\right\}\right\rangle
$$

</details>

# Injective Transformations

## Definitions and Theorems {.tabset}

### Definition 1.1.
**Injective**

A mapping $T : U \rightarrow V$ is injective if every element in $V$ is the image of at most one element in $U$. Injective mappings are also called *one-to-one*.

### Theorem 1.1.

A linear transformation $T : U \rightarrow V$ is injective iff $T(\mathbf{x}) = T(\mathbf{y}) \Rightarrow \mathbf{x}=\mathbf{y}$ for all $\mathbf{x}$ and $\mathbf{y}$ in $U$.

<details>

<summary>

*Proof*

</summary>

Let $T: U \rightarrow V$ be injective. Consider $\mathbf{x}$ and $\mathbf{y}$ in $U$, and $v$ in $V$. Then,

$$T(\mathbf{x}) = T(\mathbf{y}) = \mathbf{v}
\\ \Rightarrow T^{−1}(T(\mathbf{x})) = T^{−1}(T(\mathbf{y})) = T^{−1}(\mathbf{v})
\\ \Rightarrow \mathbf{x}= \mathbf{y}= T^{−1}(\mathbf{v}) \Rightarrow \mathbf{x}= \mathbf{y}$$

Now let $T(\mathbf{x}) = T(\mathbf{y}) \Rightarrow \mathbf{x}= \mathbf{y}$. Let the preimage of $\mathbf{v}$, $T^{-1}(\mathbf{v})$, contains to two elements $\mathbf{w},\mathbf{u}$. Then $T(\mathbf{w}) = \mathbf{v}= T(\mathbf{u}) \Rightarrow \mathbf{x}= \mathbf{y}$. So the preimage must only contain one element.

</details>

### Theorem 1.2.

A linear transformation $T : U \rightarrow V$ is injective iff $\mathcal{K}(T) = \{\bf 0\}$.

<details>

<summary>

*Proof*

</summary>

We'll start with injective $\Rightarrow\ \mathcal{K}(T) = \{0\}$:

Given we have $\mathbf{v}\rightarrow T(\mathbf{v})$ is injective, we know that $\forall \mathbf{x}, \mathbf{y}\in U, T(\mathbf{x}) = T(\mathbf{y}) \Rightarrow \mathbf{x}=\mathbf{y}$. The $\mathbf{0}_U \in \mathcal{K}(T)$ where $\mathbf{0}_U$ is $\mathbf{0}\in U$, in other words $T(\mathbf{0}_U) = \mathbf{0}_V$. Given this, $\mathbf{u}\in \mathcal{K}(T) \Rightarrow T(\mathbf{u}) = \mathbf{0}_V = T(\mathbf{0}_U) \Rightarrow \mathbf{u}= \mathbf{0}_U$.

Now we show the other way, injective $\Leftarrow\ \mathcal{K}(T) = \{0\}$:

Given $\mathcal{K}(T) = \{0\}$ and $\mathbf{u}, \mathbf{w}\in U$, letting $T(\mathbf{u}- \mathbf{w}) = \mathbf{0}$. Then, $T(\mathbf{u}- \mathbf{w}) = \mathbf{0} \Rightarrow \mathbf{u}- \mathbf{w}= \mathbf{0} \Rightarrow \mathbf{u}= \mathbf{w}$

<details>

### Theorem 1.3.

If $T : U \rightarrow V$ is an injective linear transformation and $S = \{\mathbf{u}_1, \mathbf{u}_2, \dots, \mathbf{u}_n\}$ is a linearly independent subset of $U$, then

$$R = \{T(\mathbf{u}_1), T(\mathbf{u}_2), \dots, T(\mathbf{u}_n)\}$$

is a linearly independent subset of $V$.

### Theorem 1.4.

Let $T : U \rightarrow V$ be a linear transformation and $B = \{\mathbf{u}_1, \mathbf{u}_2, \dots, \mathbf{u}_n\}$ be a basis for $U$. Then $T$ is injective iff

$$C = \{T(\mathbf{u}_1), T(\mathbf{u}_2), \dots, T(\mathbf{u}_n)\}$$

is a linearly independent subset of $V$.

### Theorem 1.5.

If $T : U \rightarrow V$ is an injective linear transformation then $\text{dim}(U) \le \text{dim}(V)$

## Examples

Let 

$T: \mathbb{P}_{2} \rightarrow \mathbb{C}^{3}$, where $T(\mathbf{p})=\left[\begin{array}{c}p(0) \\ p(0) \\ p(2)\end{array}\right]$

Is $T$ injective? Why or why not?

<details><summary>Solution</summary>

Previously we found that

$$
\mathcal{K}(T)=\left\langle\left\{-2 x+x^{2}\right\}\right\rangle
$$

By theorem 1.2, since $\mathcal{K}(T) \neq\{\mathbf{0}\}, T$ is not injective.

</details>

Example 1.2. Let $T: \mathbb{P}_{3} \rightarrow \mathbb{C}^{3}$ be given by

$$
T\left(a+b x+c x^{2}+d x^{3}\right)=\left[\begin{array}{c}
a-d \\
b+c \\
a+b-c
\end{array}\right]
$$

Is $T$ injective? Why or why not?

<details><summary>Solution</summary>

By theorem 1.5, since the dimension of $\mathbb{P}_{3}$ is 4 and the dimension of $\mathbb{C}^{3}$ is $3, T$ is not injective.

</details>

Let $T: \mathbb{P}_{2} \rightarrow \mathbb{C}^{3}$ be given by

$$
T\left(a+b x+c x^{2}\right)=\left[\begin{array}{l}
a+b \\
b+c \\
a+c
\end{array}\right]
$$

Is $T$ injective? Why or why not?

<details><summary>Solution</summary>

We find $\mathcal{K}(T)$ by solving $T(\mathbf{p})=\mathbf{0}$ as usual

$$
T\left(a+b x+c x^{2}\right)=\left[\begin{array}{l}
a+b \\
b+c \\
a+c
\end{array}\right]=\left[\begin{array}{l}
0 \\
0 \\
0
\end{array}\right]
$$

Using the definition of vector equality in $\mathbb{C}^{3}$ we obtain the system of equations

$$
\begin{aligned}
&a+b=0 \\
&b+c=0 \\
&a+c=0
\end{aligned}
$$

Which we can write as

$$
\begin{array}{r}
a+b+0 c=0 \\
0 a+b+c=0 \\
a+0 b+c=0
\end{array}
$$

And solve as usual by row-reducing the coefficient matrix: 

$$
\left[\begin{array}{lll}
1 & 1 & 0 \\
0 & 1 & 1 \\
1 & 0 & 1
\end{array}\right] \sim\left[\begin{array}{lll}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{array}\right] \Longrightarrow a=b=c=0
$$

Since

$$
\mathcal{K}(T)=\left\{\left[\begin{array}{l}
0 \\
0 \\
0
\end{array}\right]\right\}
$$

$T$ is injective.

</details>

# Surjective Transformations

## Definitions and Theorems {.tabset}

### Definition 2.1.
**Surjective**

A mapping $T : U \rightarrow V$ is surjective if every element in $V$ is the image of at least one element in $U$. Surjective mappings are also called *onto*.

### Theorem 2.1.

A linear transformation $T : U \rightarrow V$ is surjective iff for every $\mathbf{v}\in V$ there exists a $\mathbf{u}\in U$ so that $T(\mathbf{u}) = \mathbf{v}$

<details>

<summary>

*Proof*

</summary>

The first direction is trivial based on the definition.

Given for every $\mathbf{v}\in V$ there exists a $\mathbf{u}\in U$ so that $T(\mathbf{u}) = \mathbf{v}$, we can see that every preimage $T^{-1}(v) \not= \emptyset$. Thus every element $\mathbf{v}\in V$ has at least one mapping from $U$

</details>

### Theorem 2.2.

A linear transformation $T : U \rightarrow V$ is surjective iff the range of $T$ equals the codomain, $\mathcal{R}(T) = V$

<details>

<summary>

*Proof*

</summary>

Let $T$ be surjective. Then every $\mathbf{v}\in V$ is the image of at least one vector $\mathbf{u}\in U$, so

$$V \subseteq \mathcal{R}(T)$$

Since every vector $\mathbf{v}\in \mathcal{R}(T)$ is also in $V$, we have $\mathcal{R}(T) = V$.

Conversely, let

$$\mathcal{R}(T) = V$$

Then every vector in $V$ is the image of at least one vector $\mathbf{u}\in U$, so $T$ is surjective.

</details>

### Theorem 2.3.

If $T : U \rightarrow V$ is a surjective linear transformation and $S = \{\mathbf{u}_1, \mathbf{u}_2, \dots, \mathbf{u}_n\}$ spans $U$, then

$$R = \{T(\mathbf{u}_1), T(\mathbf{u}_2), \dots, T(\mathbf{u}_n)\}$$

spans $\mathcal{R}(T)$.

### Theorem 2.4.

Let $T : U \rightarrow V$ be a linear transformation and

$$B = \{\mathbf{u}_1, \mathbf{u}_2, \dots, \mathbf{u}_n\}$$

be a basis for $U$. Then $T$ is surjective iff

$$C = \{T(\mathbf{u}_1), T(\mathbf{u}_2), \dots, T(\mathbf{u}_n)\}$$

is a spanning set for $V$.

### Theorem 2.5.

If $T : U \rightarrow V$ is a surjective linear transformation then $\text{dim}(U) \ge \text{dim}(V)$

## Examples

Let $T: \mathbb{P}_{2} \rightarrow \mathbb{C}^{3}$, where $T(\mathbf{p})=\left[\begin{array}{l}p(0) \\ p(0) \\ p(2)\end{array}\right]$.

Is $T$ surjective? Why or why not?

<details><summary>Solution</summary>

an arbitrary vector in $\mathcal{R}(T)$ is

$$
\begin{aligned}
T(\mathbf{p})=& {\left[\begin{array}{l}
p(0) \\
p(0) \\
p(2)
\end{array}\right]=\left[\begin{array}{l}
a_{0}+a_{1}(0)+a_{2}(0)^{2} \\
a_{0}+a_{1}(0)+a_{2}(0)^{2} \\
a_{0}+a_{1}(2)+a_{2}(2)^{2}
\end{array}\right] } \\
=& {\left[\begin{array}{c}
a_{0} \\
a_{0} \\
a_{0}+2 a_{1}+4 a_{2}
\end{array}\right] } \\
=& a_{0}\left[\begin{array}{l}
1 \\
1 \\
1
\end{array}\right]+a_{1}\left[\begin{array}{l}
0 \\
0 \\
2
\end{array}\right]+a_{2}\left[\begin{array}{l}
0 \\
0 \\
4
\end{array}\right]
\end{aligned}
$$

Therefore

$$
\mathcal{R}(T)=\left\langle\left\{\left[\begin{array}{l}
1 \\
1 \\
1
\end{array}\right],\left[\begin{array}{l}
0 \\
0 \\
2
\end{array}\right],\left[\begin{array}{l}
0 \\
0 \\
4
\end{array}\right]\right\}\right\rangle=\left\langle\left\{\left[\begin{array}{l}
1 \\
1 \\
1
\end{array}\right],\left[\begin{array}{l}
0 \\
0 \\
2
\end{array}\right]\right\}\right\rangle
$$

Since $\mathcal{R}(T)$ is a 2-dimensional subspace of $\mathbb{C}^{3}$, which is 3-dimensional, clearly 

$$
\mathcal{R}(T) \neq \mathbb{C}^{3}
$$

therefore, by theorem $2.2, T$ is not surjective.

</details>

Let $T: \mathbb{P}_{3} \rightarrow \mathbb{C}^{3}$ be given by

$$
T\left(a+b x+c x^{2}+d x^{3}\right)=\left[\begin{array}{c}
a-d \\
b+c \\
a+b-c
\end{array}\right]
$$

Is $T$ surjective? Why or why not?

<details><summary>Solution</summary>

First we find $\mathcal{R}(T)$

$$
T\left(a+b x+c x^{2}+d x^{3}\right)=\left[\begin{array}{c}
a-d \\
b+c \\
a+b-c
\end{array}\right]=a\left[\begin{array}{l}
1 \\
0 \\
1
\end{array}\right]+b\left[\begin{array}{l}
0 \\
1 \\
1
\end{array}\right]+c\left[\begin{array}{r}
0 \\
1 \\
-1
\end{array}\right]+d\left[\begin{array}{r}
-1 \\
0 \\
0
\end{array}\right]
$$

So

$$
\mathcal{R}(t)=\left\langle\left\{\left[\begin{array}{l}
1 \\
0 \\
1
\end{array}\right],\left[\begin{array}{l}
0 \\
1 \\
1
\end{array}\right],\left[\begin{array}{r}
0 \\
1 \\
-1
\end{array}\right],\left[\begin{array}{r}
-1 \\
0 \\
0
\end{array}\right]\right\}\right\rangle
$$

Now we can check if these vectors span $\mathbb C^3$.

$$
\left[\begin{array}{rrrr}
1 & 0 & 0 & -1 \\
0 & 1 & 1 & 0 \\
1 & 1 & -1 & 0
\end{array}\right] \sim\left[\begin{array}{rrrr}
1 & 0 & 0 & -1 \\
0 & 1 & 1 & \frac{1}{2} \\
0 & 0 & 1 & -\frac{1}{2}
\end{array}\right]
$$

The system will be consistent for every vector in $\mathbb C^3$. So $\mathcal{R}(T)=\mathbb{C}^{3}$, and $T$ is surjective.

</details>

Let $T: \mathbb{P}_{2} \rightarrow \mathbb{C}^{3}$ be given by

$$
T\left(a+b x+c x^{2}\right)=\left[\begin{array}{l}
a+b \\
b+c \\
a+c
\end{array}\right]
$$

Is $T$ surjective? Why or why not?

<details><summary>Solution</summary>

$$
T\left(a+b x+c x^{2}+d x^{3}\right)=\left[\begin{array}{l}
a+b \\
b+c \\
a+c
\end{array}\right]=a\left[\begin{array}{l}
1 \\
0 \\
1
\end{array}\right]+b\left[\begin{array}{l}
1 \\
1 \\
0
\end{array}\right]+c\left[\begin{array}{l}
0 \\
1 \\
1
\end{array}\right]
$$

So

$$
\mathcal{R}(t)=\left\langle\left\{\left[\begin{array}{l}
1 \\
0 \\
1
\end{array}\right],\left[\begin{array}{l}
1 \\
1 \\
0
\end{array}\right],\left[\begin{array}{l}
0 \\
1 \\
1
\end{array}\right]\right\}\right\rangle
$$

$$
{\left[\begin{array}{lll}
1 & 0 & 1 \\
1 & 1 & 0 \\
0 & 1 & 1
\end{array}\right] \sim\left[\begin{array}{lll}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{array}\right]}
$$

Since there's a pivot in every row of the coefficient matrix, so $\mathcal{R}(T)=\mathbb{C}^{3}$, and $T$ is surjective.

</details>

# Isomorphism

## Definitions and Theorems {.tabset}

### Definition 3.1.

**Identity Transformation**

If $V$ is a vector space, the identity transformation on $V$ is defined by $I_V : V \rightarrow V$, $I_V(\mathbf{v}) = \mathbf{v}, \forall\mathbf{v}\in V$

### Definition 3.2.

**Invertible Transformation**

A linear transformation $T : U \rightarrow V$ is invertible if there exists a transformation $S : V \rightarrow U$ such that

$$S \circ T = I_U\text{ and }T \circ S = I_V$$

$S$ is called the inverse of $T$ and we use the same inverse notation for transformations as for matrices:

$$S = T^{−1}$$

### Definition 3.3.

**Bijective**

A mapping that is both injective and surjective is called bijective.

### Theorem 3.1.

**Bijective is Invertible**

A linear transformation $T : U \rightarrow V$ is invertible iff it is bijective.

### Theorem 3.2.

**Inverse is Unique**

The inverse of an invertible linear transformation is unique.

<details>

<summary>

*Proof*

</summary>

Let $S: V \rightarrow U$ and $W: V \rightarrow U$ be inverses of $T: U \rightarrow V$, then

$$(S \circ T)(\mathbf{u}) = \mathbf{u}= (W \circ T)(\mathbf{u})
\\ \Rightarrow S(T(\mathbf{u})) = \mathbf{u}= W(T(\mathbf{u}))
\\ \Rightarrow S(\mathbf{v}) = \mathbf{u}= W(\mathbf{v})$$

</details>

### Definition 3.4.

**Isomorphism**

An isomorphism is an invertible linear transformation.

### Definition 3.5.

**Isomorphic Vector Space**

Two vector spaces $U$ and $V$ are isomorphic if there exists an invertible linear transformation $T : U \rightarrow V$. If $U$ is isomorphic to $V$ we write $U \cong V$

### Theorem 3.3.

**Isomorphism and Dimension**

If $U$ and $V$ are isomorphic vector spaces, then $\text{dim}(U) = \text{dim}(V)$

<details>

<summary>

*Proof*

</summary>

Since $U$ and $V$ are isomorphic, there exists an invertible linear transformation $T : U \rightarrow V$. Since $T$ is injective, by theorem 1.5,

$$\text{dim}(U) \le \text{dim}(V)$$

Since $T$ is surjective, by theorem 2.5,

$$\text{dim}(U) \ge \text{dim}(V)$$

Therefore

$$\text{dim}(U) = \text{dim}(V)$$

</details>

### Theorem 3.4.

**Composition of the Inverse**

If $T : U \rightarrow V$ is an invertible linear transformation, $\mathbf{u}\in U$ and $\mathbf{v}\in V$, then

$$T(T^{−1}(\mathbf{v})) = \mathbf{v}, \forall\mathbf{v}\in V$$

and

$$T^{−1}(T(\mathbf{u})) = \mathbf{u}, \forall\mathbf{u}\in U$$

### Theorem 3.5.

**Inverse of the Inverse**

If $T : U \rightarrow V$ is an invertible linear transformation, then $T^{−1}: V \rightarrow U$ is also an invertible linear transformation and $(T^{−1})^{−1} = T$

### Theorem 3.6.

\*\*Inverse of a Composition\*

If $T : U \rightarrow V$ and $S : V \rightarrow W$ are invertible linear transformations, then $S \circ T : U \rightarrow W$ is also an invertible linear transformation and

$$(S \circ T)^{−1} = T^{−1} \circ S^{−1}$$

### Definition 3.6.

**Rank of a Linear Transformation**

If $T : U \rightarrow V$ is a linear transformation, then the rank of $T$ is the dimension of the range of $T$:

$$r(T) = \text{dim}(R(T))$$

### Definition 3.7.

**Nullity of a Linear Transformation**

If $T : U \rightarrow V$ is a linear transformation, then the nullity of $T$ is the dimension of the kernel of $T$:

$$n(T) = \text{dim}(K(T))$$

### Theorem 3.7.

**Rank of a Surjective Linear Transformation**

Let $T : U \rightarrow V$ be a linear transformation. Then $T$ is surjective iff

$$r(T) = \text{dim}(V)$$

<details>

<summary>

*Proof*

</summary>

If $T$ is surjective, then $\mathcal{R}(T) = V$, therefore

$$r(T) = \text{dim}(\mathcal{R}(T)) = \text{dim}(V)$$

Conversely, if $r(T) = \text{dim}(V)$, then $\text{dim}(\mathcal{R}(T)) = \text{dim}(V)$. Since $\mathcal{R}(T) \subseteq V$,

$$\mathcal{R}(T) = V$$

</details>

### Theorem 3.8.

**Nullity of an Injective Linear Transformation**

Let $T : U \rightarrow V$ be a linear transformation. Then $T$ is injective iff $n(T) = 0$

### Theorem 3.9.

**Rank \### Theorem for Linear Transformations**

Let $T : U \rightarrow V$ be a linear transformation. Then

$$r(T) + n(T) = \text{dim}(U)$$

## Examples

Let $T: \mathbb{P}_{2} \rightarrow \mathbb{C}^{3}$, where 

$$T(\mathbf{p})=\left[\begin{array}{l}p(0) \\ p(0) \\ p(2)\end{array}\right]$$

Is $T$ invertible? Why or why not?

<details><summary>Solution</summary>

We saw previously that $T$ is neither injective nor surjective, so $T$ is not invertible.

</details>

Let $T: \mathbb{P}_{3} \rightarrow \mathbb{C}^{3}$ be given by

$$
T\left(a+b x+c x^{2}+d x^{3}\right)=\left[\begin{array}{c}
a-d \\
b+c \\
a+b-c
\end{array}\right]
$$

Is $T$ invertible? Why or why not?

<details><summary>Solution</summary>

$$
\operatorname{dim}\left(\mathbb{P}_{3}\right)=4 \neq 3=\operatorname{dim}\left(\mathbb{C}^{3}\right)
$$
So it is not invertible.

</details>

Let $T: \mathbb{P}_{2} \rightarrow \mathbb{C}^{3}$ be given by

$$
T\left(a+b x+c x^{2}\right)=\left[\begin{array}{l}
a+b \\
b+c \\
a+c
\end{array}\right]
$$

Is $T$ invertible? Why or why not?

<details><summary>Solution</summary>

we found the kernel to be

$$
\mathcal{K}(T)=\left\{\left[\begin{array}{l}
0 \\
0 \\
0
\end{array}\right]\right\}
$$

so we know $T$ is injective, and $n(T)=0$. The Rank Theorem says

$$
n(T)+r(T)=\operatorname{dim}\left(\mathbb{P}_{2}\right)
$$

so we have $0+r(T)=3 \Rightarrow r(T)=3$. Theorem $3.7$ tells us that $T$ is surjective, which means it's also invertible.

</details>














