---
title: "Vector Spaces and Subspaces"
author: "Brody Erlandson"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 2
---

\include{mathCommands}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Vector Spaces

## Definitions and Theorems {.tabset}

### Definition 1.1.
**Vector Space**

Given:

- A set $V$ of vectors
- A set $F$ of scalars
- A definition of vector addition, $\u + \v$, where $\u, \v \in V$
- A definition of scalar multiplication, $\alpha\u$, where $\u$ is in $V$ and $\alpha$ is in $F$

If $\u, \v, \w \in V$, and $\alpha, \beta \in F$, $V$ is a vector space over $F$ when the following properties (called axioms) are satisfied:

1. Additive Closure: $\u, \v \in V \Rightarrow (\u + \v) \in V$ ($V$ is closed under vector addition.)
2. Scalar Closure: $\u \in V\text{ and }\alpha \in F \Rightarrow (\alpha\u) \in V$ ($V$ is closed under scalar multiplication.)
3. Commutativity: $\u, \v \in V \Rightarrow \u + \v = \v + \u$
4. Additive Associativity: $\u, \v \in V \Rightarrow \u + (\v + \w) = (\u + \v) + \w$
5. Zero Vector: $\exists\ \0 \in V\text{ such that }\u + \0 = \u, \forall\u \in V$
6. Additive Inverses: $\forall\ \u \in V, \exists −\u \in V\text{ such that }\u + (−\u) = \0$
7. Scalar Multiplication Associativity: $\alpha,\beta \in F\text{ and }\u \in V \Rightarrow \alpha(\beta\u) = (\alpha\beta)\u$
8. Distributivity across Vector Addition: $\u, \v \in V\text{ and } \alpha \in F \Rightarrow \alpha(\u + \v) = \alpha\u + \alpha\v$
9. Distributivity across Scalar Addition: $\alpha,\beta \in F\text{ and }\u \in V \Rightarrow (\alpha + \beta)\u = \alpha\u + \beta\u$
10. One: $1\u = \u$

### Theorem 1.1. 

Given a vector space $V$ over $F$, $\alpha\0 = \0\ \forall\ \alpha \in F$.

<details><summary>*Proof*</summary>

$$\alpha\0 = \alpha\0+ \0 
\\ = \alpha\0 + (\alpha\0 + -(\alpha\0))
\\ = (\alpha\0 + \alpha\0) + -(\alpha\0)
\\ = \alpha(\0 + \0) + -(\alpha\0)
\\ = \alpha(\0) + -(\alpha\0)
\\ = \0$$

</details> \newline 

### Theorem 1.2. 
**Uniqueness of Additive Inverse**

The additive inverse of any vector in a vector space is unique.

<details><summary>*Proof*</summary>

$$ -\u+\0 = -\u+\0 \\
 -\u+\u+\v = -\u+\u+\w \\
 \0+\v = \0+\w \\
 \v = \w \\$$

</details> \newline 

### Theorem 1.3.
**Properties of Vector Spaces**

Let $V$ be a vector space over $F$. Then for each $\u \in V$ and $\alpha \in F$:

1. $0\u = \0$
2. $\alpha\0 = \0$
3. $−\u = (−1)\u$

## Examples

### $\C^n$

Lets start with a familiar vector space of column vectors in $\C^n$ over the field of $\C$. 

$$V = \Bigg\{\vddd{u_1}{\vdots}{u_n}\Bigg|\ \forall\ i,\ u_i \in \C\Bigg\} \\ F = \C$$

Definition of addition is $[\u + \v]_i = u_i + v_i$ \newline

Definition of scalar multiplication is $[\alpha\u]_i = \alpha u_i$ \newline

With these definitions we have to show the 10 axioms are satisfied 

<details><summary>*First 3 axioms shown*</summary> 

Let $\u, \v \in \C^n$ and $\alpha \in \C$, then 

$$\u + \v = \vddd{u_1}{\vdots}{u_n} + \vddd{v_1}{\vdots}{v_n} = \vddd{u_1+v_1}{\vdots}{u_n+v_n} = \vddd{v_1+u_1}{\vdots}{v_n+u_n} = \u + \v$$

From the above we can see that $u_i + v_i \in \C$ so $\u + \v \in \C^n$. Also we can see that commutativity is satisfied. Also,

$$\alpha\u = \alpha\vddd{u_1}{\vdots}{u_n} = \vddd{\alpha u_1}{\vdots}{\alpha u_n}$$

We know $\alpha u_1 \in \C$, so $\alpha\u \in \C^n$. 

</details>

### Zero Vector Space

$$V = \{\0\} \\ F = F$$

Definition of addition is $[\0 + \0]_i = 0_i + 0_i$ \newline

Definition of scalar multiplication is $[\alpha\0]_i = \alpha 0_i$ \newline

<details><summary>*First 4 through 6 axioms shown*</summary> 

4. Additive Associativity: $\u, \v \in V \Rightarrow \u + (\v + \w) = (\u + \v) + \w$

$$\0 + (\0 + \0) = \0 + (\vddd{0+0}{\vdots}{0+0}) = \vddd{0+0+0}{\vdots}{0+0+0} = (\vddd{0+0}{\vdots}{0+0}) + \0 = (\0 + \0) + \0$$

5. Zero Vector: $\exists\ \0 \in V\text{ such that }\u + \0 = \u, \forall\u \in V$

$$\0 + \0 = \vddd{0+0}{\vdots}{0+0} = \0$$

6. Additive Inverses: $\forall\ \u \in V, \exists −\u \in V\text{ such that }\u + (−\u) = \0$

$$\0 - \0 = \vddd{0-0}{\vdots}{0-0} = \0$$

</details>

### $P_n$

$$V = \{p(x)=\alpha_0 + \alpha_1x+\alpha_2x^2+\dots+\alpha_nx^n |\ \forall\ i\ \alpha_i \in \C\} \\ F = \C$$

Definition of Addition is $(p+q)(x)=p(x)+q(x)$ \newline

Definition of Multiplication is $(\alpha p)(x) = \alpha p(x)$

<details><summary>*First 7 through 10 axioms shown*</summary> 

8. Distributivity across Vector Addition: $\u, \v \in V\text{ and } \alpha \in F \Rightarrow \alpha(\u + \v) = \alpha\u + \alpha\v$

$$ \alpha(p+q)(x) = \alpha(p(x)+q(x)) 
\\ = \alpha((\beta_0 + \beta_1x+\beta_2x^2+\dots+\beta_nx^n) + (\gamma_0 + \gamma_1x+\gamma_2x^2+\dots+\gamma_nx^n))
\\ = \alpha((\beta_0+\gamma_0) + (\beta_1+\gamma_1)x+(\beta_2+\gamma_2)x^2+\dots+(\beta_n+\gamma_n)x^n)
\\ = (\alpha(\beta_0+\gamma_0) + \alpha(\beta_1+\gamma_1)x+\alpha(\beta_2+\gamma_2)x^2+\dots+\alpha(\beta_n+\gamma_n)x^n)
\\ = ((\alpha\beta_0+\alpha\gamma_0) + (\alpha\beta_1+\alpha\gamma_1)x+(\alpha\beta_2+\alpha\gamma_2)x^2+\dots+(\alpha\beta_n+\alpha\gamma_n)x^n)
\\ = (\alpha\beta_0+\alpha\beta_1x+\alpha\beta_2x^2+\dots+\alpha\beta_nx^n) + (\alpha\gamma_0+\alpha\gamma_1x++\alpha\gamma_2x^2+\dots+\alpha\gamma_nx^n)
\\ = \alpha p(x)+\alpha q(x)$$

9. Distributivity across Scalar Addition: $\alpha,\beta \in F\text{ and }\u \in V \Rightarrow (\alpha + \beta)\u = \alpha\u + \beta\u$

$$ ((\alpha+\beta)p)(x) = (\alpha+\beta)p(x) 
\\ = (\alpha+\beta)(\gamma_0 + \gamma_1x+\gamma_2x^2+\dots+\gamma_nx^n)
\\ = (\alpha+\beta)\gamma_0 + (\alpha+\beta)\gamma_1x+(\alpha+\beta)\gamma_2x^2+\dots+(\alpha+\beta)\gamma_nx^n)
\\ = (\alpha\gamma_0+\beta\gamma_0) + (\alpha\gamma_1+\beta\gamma_1)x+\dots+(\alpha\gamma_n+\beta\gamma_n)x^n
\\ = \alpha\gamma_0+\beta\gamma_0 + \alpha\gamma_1x+\beta\gamma_1x+\dots+\alpha\gamma_nx^n+\beta\gamma_nx^n
\\ = \alpha p(x)+\beta p(x)$$

10. One: $1\u = \u$

$$ (1p)(x) = 1p(x) 
\\ = 1(\gamma_0 + \gamma_1x+\gamma_2x^2+\dots+\gamma_nx^n)
\\ = 1\gamma_0 + 1\gamma_1x+1\gamma_2x^2+\dots+1\gamma_nx^n
\\ = p(x)$$

</details>

### Is it a Vector Space?

$$V = \Big\{ \vdd{x}{y} | x,y \in \C\Big\} \\ F=\C$$

Addition: $\vdd{x}{y} +  \vdd{w}{z} =  \vdd{0}{0}$

Multiplication: $\alpha\vdd{x}{y} = \vdd{\alpha x}{\alpha y}$

<details><summary>*Solution*</summary> 

No it is not, because if we let $x\not= 0$ and $y \not= 0$

$\vdd{x}{y} +  \vdd{0}{0} =  \vdd{0}{0}$

</details>

# Subspaces

## Definitions and Theorems {.tabset}

### Definition 2.1.
**Subset**

If $A$ and $B$ are sets, then $A$ is a subset of $B$, written $A \subseteq B$, if every element in $A$ is in $B$.

### Definition 2.2. 
**Subspace**

Let $H$ be a non-empty subset of a vector space $V$. $H$ is a subspace of $V$ if $H$ is closed under vector addition and scalar multiplication.

### Theorem 2.1.

If $S = \{\v_1, \v_2, \v_3, \dots, \v_p\}$ is a subset of a vector space $V$, then $\span{S}$ is a subspace of $V$.

<details><summary>*Proof*</summary>. 

Let $\u, \w \in \span{S}$ and $\gamma,\delta \in F$, then

$$\gamma\u + \delta\w = \gamma\sum_{i=1}^n\alpha_i\v_i + \delta\sum_{i=1}^n\beta_i\v_i = \sum_{i=1}^n (\gamma\alpha_i + \delta\beta_i)\v_i$$

So given $(\gamma\alpha_i + \delta\beta_i) \in F$, we know $\gamma\u + \delta\w \in \span{S}$. Thus $\span{S}$ is a subspace.

</details> \newline 

### Theorem 2.2.
**Null Space is a Subspace**

If $A$ is an $m \times n$ matrix, $\mathcal{N}(\A)$ is a subspace of $\C^n$.

<details><summary>*Proof*</summary>

$$\A(\alpha\u + \beta\v) = \A\alpha\u + \A\beta\v = \alpha\A\u + \beta\A\v
= \alpha\0 + \beta\0 = \0$$

</details> \newline 

### Theorem 2.3.
**Column Space is a Subspace**

If $\A$ is an $m \times n$ matrix, $\mathcal C(\A)$ is a subspace of $\C^m$.

### Theorem 2.4.
**Row Space is a Subspace**

If $\A$ is an $m \times n$ matrix, $\mathcal R(A)$ is a subspace of $\C^n$.

## Examples

Let,

$$H = \{\u\in\C^3|\u^T = [3t\ \ 0\ \ -7t], t\in \C\}$$

Is $H$ a subspace of $\C^3$?

<details><summary>*Solution*</summary> 

If we let $\u, \v \in H$ and $s,t,\alpha,\beta \in \C$, then:

$$\alpha\u+\beta\v = \alpha\vddd{3t}{0}{-7t}+\beta\vddd{3s}{0}{-7s}
\\ = \vddd{3(\alpha t + \beta s)}{0}{-7(\alpha t + \beta s)} \in H\text{ given }(\alpha t + \beta s) \in \C$$

So it is a subspace.

We could also see that $H = \span{\{\u\}}$, and $\{\u\} \subseteq \C^3$, so it is a subspace.

</details>

Is $\emptyset$ a subspace?

<details><summary>*Solution*</summary> 

No, because $\not\exists\0\in\emptyset$

</details>

Is $\{\0\}$ a subspace of every vector space?

<details><summary>*Solution*</summary> 

Yes! We already know $\{\0\}$ is a vector space, so its closed under addition and scalar multiplication. Moreover, we know that every vector space must contain a $\0$ by the 5th axiom. So 

$$\{\0\} \subseteq V\text{ and }\span{\{\0\}} = \{\0\}$$

</details>
